sudo: required
services:
  - docker

before_install:
  - docker build -t yyfmichaelyan/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true yyfmichaelyan/docker-react npm run test -- --coverage

language: generic
